### ISSUE TITLE
i'm struggling on installing it

### ISSUE THREAD

**Issue by ghost** [myrtleTree33/kuler2gpl#2]
the installing documentation is far incomplete, i only get error messages, and no kuler2gpl installed at all - in which directory should we enter "npm install -g kuler2gpl" from the terminal? anywhere, outside or inside the package folder? i tried all 3, none worked

**Comment by myrtleTree33** [comment]
Hello nitrofurano,

The module is a command-line utility; it does not do installation in the folder of palettes.

Entering `npm install -g kuler2gpl` installs the package as an NPM global.

You would have to install `NodeJS` prior to that.  May I refer you to one of the scripts at https://gist.github.com/isaacs/579814 , which works pretty well.

Do let me know should you have any issue.

Cheers!
